-- Run this in Supabase: SQL Editor → New query → Run
-- Then insert rows. For images you can use:
-- 1) Local files already in this project, e.g. /images/products/bedroom/bead1.png
-- 2) Or a public Storage URL from a bucket named "products"

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text,
  price numeric not null,
  image text,
  tag text,
  description text,
  material text,
  finish text,
  dimensions text,
  delivery text
);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
  on public.products
  for select
  to anon, authenticated
  using (true);

-- Example row using a local image path (works with files in woodcraft/public)
insert into public.products (name, slug, category, price, image, tag)
values (
  'Sheesham Storage Bed with LED Headboard',
  'sheesham-storage-bed-led-headboard',
  'Bedroom',
  95000,
  '/images/products/bedroom/bead1.png',
  'New'
)
on conflict (slug) do nothing;
